package com.grupo1.FlipFloppin.enums;

public enum Provincia {
    CATAMARCA, CORRIENTES, CHACO, FORMOSA, JUJUY, MISIONES, TUCUMÁN, SALTA, SANTIAGO_DEL_ESTERO, LA_RIOJA, MENDOZA, SAN_JUAN, SAN_LUIS, CHUBUT, LA_PAMPA, NEUQUÉN, RÍO_NEGRO, SANTA_CRUZ,TIERRA_DEL_FUEGO,CÓRDOBA, ENTRE_RÍOS, SANTA_FE}
